"""completed field added in invoices table for picker and checker flow completed

Revision ID: 1110735c16cb
Revises: 90d5b57bed60
Create Date: 2025-12-12 11:53:45.701734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1110735c16cb'
down_revision: Union[str, Sequence[str], None] = '90d5b57bed60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_completed', sa.Boolean(), nullable=False,server_default=sa.text("0")))
        
    with op.batch_alter_table('invoices') as batch_op:
        batch_op.alter_column('is_completed', server_default=None)


    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('is_completed')

    # ### end Alembic commands ###
