"""InvoicesProduct table connect to ScanStatusEnum

Revision ID: 1eb6a7def7bb
Revises: f6bbd66f386c
Create Date: 2025-11-19 11:50:58.597229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eb6a7def7bb'
down_revision: Union[str, Sequence[str], None] = 'f6bbd66f386c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_product_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scan_status', sa.Enum('success', 'auto_confirm', 'auto_fallback', 'auto_multi', 'manual', name='scanstatusenum'), nullable=True))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rack_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_transactions_rack_id", 'rack_master', ['rack_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint("fk_transactions_rack_id", type_='foreignkey')
        batch_op.drop_column('rack_id')

    with op.batch_alter_table('invoice_product_list', schema=None) as batch_op:
        batch_op.drop_column('scan_status')

    # ### end Alembic commands ###
