"""add new field invoice_type with enum purchase,sell

Revision ID: 2a63c800b33d
Revises: 7c52149d3e77
Create Date: 2025-11-05 14:28:54.500641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a63c800b33d'
down_revision: Union[str, Sequence[str], None] = '7c52149d3e77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_type', sa.Enum('purchase', 'sell', name='invoicetype'), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('invoice_type')

    # ### end Alembic commands ###
