"""in settings table added field show_actual_qty

Revision ID: 3b44d491dbcf
Revises: 6f0d96addc2d
Create Date: 2025-11-12 13:01:48.346841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b44d491dbcf'
down_revision: Union[str, Sequence[str], None] = '6f0d96addc2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('invoices', schema=None) as batch_op:
    #     batch_op.alter_column('invoice_type',
    #            existing_type=sa.VARCHAR(length=8),
    #            nullable=True)

    # with op.batch_alter_table('rack_master', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'users', ['user_assigned'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('system_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_actual_qty', sa.Boolean(), nullable=True))

    # with op.batch_alter_table('tray_master', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'invoices', ['current_invoice_no'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('tray_master', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'invoices', ['current_invoice_no'], ['id'])

    with op.batch_alter_table('system_config', schema=None) as batch_op:
        batch_op.drop_column('show_actual_qty')

    # with op.batch_alter_table('rack_master', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'users', ['user_assigned'], ['id'])

    # with op.batch_alter_table('invoices', schema=None) as batch_op:
    #     batch_op.alter_column('invoice_type',
    #            existing_type=sa.VARCHAR(length=8),
    #            nullable=False)

    # ### end Alembic commands ###
