"""one invoice has multiple trays

Revision ID: 3da09bcd592f
Revises: c54946e37829
Create Date: 2025-11-21 16:07:04.856857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3da09bcd592f'
down_revision: Union[str, Sequence[str], None] = 'c54946e37829'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tray_master', schema=None) as batch_op:
        batch_op.alter_column('current_invoice_no',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('uq_tray_master_current_invoice_no'), type_='unique')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tray_master', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_tray_master_current_invoice_no'), ['current_invoice_no'])
        batch_op.alter_column('current_invoice_no',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
