"""transaction table OperationStatus enum added

Revision ID: 552d6bd6690b
Revises: 6bea99d1b827
Create Date: 2025-12-08 15:54:31.415124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '552d6bd6690b'
down_revision: Union[str, Sequence[str], None] = '6bea99d1b827'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_metrics', schema=None) as batch_op:
        batch_op.alter_column('operation_status',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('operation_status', sa.Enum('checker_end', 'picker_end', 'packer_end', name='operationstatus'), nullable=True))

    # with op.batch_alter_table('tray_master', schema=None) as batch_op:
    #     batch_op.alter_column('id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False,
    #            autoincrement=True)
    #     batch_op.create_index(batch_op.f('ix_tray_master_id'), ['id'], unique=False)
    #     batch_op.create_unique_constraint(None, ['tray_no'])
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'invoices', ['current_invoice_no'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('tray_master', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'invoices', ['current_invoice_no'], ['id'])
    #     batch_op.drop_constraint(None, type_='unique')
    #     batch_op.drop_index(batch_op.f('ix_tray_master_id'))
    #     batch_op.alter_column('id',
    #            existing_type=sa.INTEGER(),
    #            nullable=True,
    #            autoincrement=True)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('operation_status')

    with op.batch_alter_table('performance_metrics', schema=None) as batch_op:
        batch_op.alter_column('operation_status',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)

    # ### end Alembic commands ###
