"""performance_metrics table created

Revision ID: 6bea99d1b827
Revises: a6c19aecd34f
Create Date: 2025-12-08 13:14:04.533186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bea99d1b827'
down_revision: Union[str, Sequence[str], None] = 'a6c19aecd34f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance_metrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('invoice_id', sa.String(), nullable=True),
    sa.Column('operation_status', sa.Enum('checker_end', 'picker_end', 'packer_end', name='operationstatus'), nullable=False),
    sa.Column('invoice_start_time', sa.String(), nullable=True),
    sa.Column('invoice_end_time', sa.String(), nullable=True),
    sa.Column('line_items', sa.Integer(), nullable=True),
    sa.Column('time_to_pick', sa.Integer(), nullable=True),
    sa.Column('total_scans', sa.Integer(), nullable=True),
    sa.Column('median_time_btw_2_scans', sa.Integer(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id', 'operation_status', name='uq_invoice_operation')
    )
    with op.batch_alter_table('performance_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_performance_metrics_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_performance_metrics_id'))

    op.drop_table('performance_metrics')
    # ### end Alembic commands ###
