"""In tray_master table set current_invoice_no to one-to-one field

Revision ID: 6f0d96addc2d
Revises: ecd76df8cb4f
Create Date: 2025-11-10 11:25:19.478022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f0d96addc2d'
down_revision: Union[str, Sequence[str], None] = 'ecd76df8cb4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('_alembic_tmp_invoices')
    # with op.batch_alter_table('invoices', schema=None) as batch_op:
    #     batch_op.alter_column('invoice_type',
    #            existing_type=sa.VARCHAR(length=8),
    #            nullable=True)

    # with op.batch_alter_table('rack_master', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'users', ['user_assigned'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('tray_master', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_tray_master_current_invoice_no', ['current_invoice_no'])
        # batch_op.drop_constraint('fk_tray_master_current_invoice_no', type_='foreignkey')
        # batch_op.create_foreign_key('fk_tray_master_current_invoice_no', 'invoices', ['current_invoice_no'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tray_master', schema=None) as batch_op:
        # batch_op.drop_constraint('fk_tray_master_current_invoice_no', type_='foreignkey')
        # batch_op.create_foreign_key('fk_tray_master_current_invoice_no', 'invoices', ['current_invoice_no'], ['id'])
        batch_op.drop_constraint('uq_tray_master_current_invoice_no', type_='unique')

    # with op.batch_alter_table('rack_master', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'users', ['user_assigned'], ['id'])

    # with op.batch_alter_table('invoices', schema=None) as batch_op:
    #     batch_op.alter_column('invoice_type',
    #            existing_type=sa.VARCHAR(length=8),
    #            nullable=False)

    # op.create_table('_alembic_tmp_invoices',
    # sa.Column('id', sa.VARCHAR(), nullable=False),
    # sa.Column('priority', sa.VARCHAR(length=6), nullable=False),
    # sa.Column('invoice_no', sa.VARCHAR(), nullable=False),
    # sa.Column('invoice_date', sa.VARCHAR(), nullable=False),
    # sa.Column('party_id', sa.VARCHAR(), nullable=True),
    # sa.Column('status', sa.VARCHAR(length=11), nullable=False),
    # sa.Column('created_at', sa.VARCHAR(), nullable=True),
    # sa.Column('started_at', sa.VARCHAR(), nullable=True),
    # sa.Column('updated_at', sa.VARCHAR(), nullable=True),
    # sa.Column('invoice_type', sa.VARCHAR(length=8), nullable=True),
    # sa.ForeignKeyConstraint(['party_id'], ['party_master.id'], ondelete='SET NULL'),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('invoice_no')
    # )
    # # ### end Alembic commands ###
