"""invoice_type nallabel false

Revision ID: 81ee5db7e3db
Revises: 2a63c800b33d
Create Date: 2025-11-05 14:32:11.589904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81ee5db7e3db'
down_revision: Union[str, Sequence[str], None] = '2a63c800b33d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('invoice_type',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('invoice_type',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)

    # ### end Alembic commands ###
