"""InvoiceProductList table added picker,checker scan_quantity and status

Revision ID: 90d5b57bed60
Revises: 552d6bd6690b
Create Date: 2025-12-11 11:08:34.825375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90d5b57bed60'
down_revision: Union[str, Sequence[str], None] = '552d6bd6690b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_product_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picker_scanned_qty', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('picker_scan_status', sa.Enum('success', 'auto_confirm', 'auto_fallback', 'auto_multi', 'manual', name='scanstatusenum'), nullable=True))
        batch_op.add_column(sa.Column('checker_scanned_qty', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('checker_scan_status', sa.Enum('success', 'auto_confirm', 'auto_fallback', 'auto_multi', 'manual', name='scanstatusenum'), nullable=True))
        batch_op.drop_column('scan_status')
        batch_op.drop_column('scanned_qty')


    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('invoice_product_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scanned_qty', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('scan_status', sa.VARCHAR(length=13), nullable=True))
        batch_op.drop_column('checker_scan_status')
        batch_op.drop_column('checker_scanned_qty')
        batch_op.drop_column('picker_scan_status')
        batch_op.drop_column('picker_scanned_qty')

    # ### end Alembic commands ###
