"""InvoiceMetadata table set invoice_id as one-to-one

Revision ID: 993c4334f690
Revises: b5c6e28e1628
Create Date: 2025-11-03 15:55:44.988268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '993c4334f690'
down_revision: Union[str, Sequence[str], None] = 'b5c6e28e1628'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_metadata', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_invoice_metadata_invoice_id', ['invoice_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_metadata', schema=None) as batch_op:
        batch_op.drop_constraint('uq_invoice_metadata_invoice_id', type_='unique')

    # ### end Alembic commands ###
