"""added table rack_master,tray_master. Add rack_no field in ProductMaster,InvoiceProdutctList

Revision ID: 9f438c83bb74
Revises: 81ee5db7e3db
Create Date: 2025-11-05 14:57:29.239634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f438c83bb74'
down_revision: Union[str, Sequence[str], None] = '81ee5db7e3db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rack_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rack_no', sa.String(length=100), nullable=False),
    sa.Column('rack_name', sa.String(length=255), nullable=False),
    sa.Column('user_assigned', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_assigned'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rack_no')
    )
    with op.batch_alter_table('rack_master', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rack_master_id'), ['id'], unique=False)

    op.create_table('tray_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tray_no', sa.String(length=100), nullable=False),
    sa.Column('tray_qr_value', sa.String(length=255), nullable=True),
    sa.Column('current_invoice_no', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_invoice_no'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tray_master', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tray_master_id'), ['id'], unique=False)

    with op.batch_alter_table('invoice_product_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rack_no', sa.String(), nullable=True))

    with op.batch_alter_table('product_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rack_no', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_master', schema=None) as batch_op:
        batch_op.drop_column('rack_no')

    with op.batch_alter_table('invoice_product_list', schema=None) as batch_op:
        batch_op.drop_column('rack_no')

    with op.batch_alter_table('tray_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tray_master_id'))

    op.drop_table('tray_master')
    with op.batch_alter_table('rack_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rack_master_id'))

    op.drop_table('rack_master')
    # ### end Alembic commands ###
