"""product master composite unique constraint check

Revision ID: a6c19aecd34f
Revises: abed5df82a3a
Create Date: 2025-11-28 18:49:06.111694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6c19aecd34f'
down_revision: Union[str, Sequence[str], None] = 'abed5df82a3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_master', schema=None) as batch_op:
        batch_op.alter_column('mfg_date',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('division',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('unique_product_batch'), type_='unique')
        batch_op.create_unique_constraint('unique_product_batch', ['item_code', 'batch_number', 'expiry_date', 'mrp'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_master', schema=None) as batch_op:
        batch_op.drop_constraint('unique_product_batch', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('unique_product_batch'), ['product_name', 'batch_number', 'expiry_date', 'mrp'])
        batch_op.alter_column('division',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('mfg_date',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
