"""party_master table add composite unique constraint

Revision ID: abed5df82a3a
Revises: 3da09bcd592f
Create Date: 2025-11-28 17:49:43.222717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abed5df82a3a'
down_revision: Union[str, Sequence[str], None] = '3da09bcd592f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('party_master', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_party_master_fields', ['party_code', 'party_name', 'party_address'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('party_master', schema=None) as batch_op:
        batch_op.drop_constraint('uq_party_master_fields', type_='unique')

    # ### end Alembic commands ###
