"""Add unique constraint on product master

Revision ID: b5c6e28e1628
Revises: e08d0a7cddd8
Create Date: 2025-10-27 12:32:11.810963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5c6e28e1628'
down_revision: Union[str, Sequence[str], None] = 'e08d0a7cddd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_master', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_product_batch', ['product_name', 'batch_number', 'expiry_date', 'mrp'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_master', schema=None) as batch_op:
        batch_op.drop_constraint('unique_product_batch', type_='unique')

    # ### end Alembic commands ###
