"""InvoiceProductId added in transaction

Revision ID: c54946e37829
Revises: 1eb6a7def7bb
Create Date: 2025-11-21 12:55:21.734776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c54946e37829'
down_revision: Union[str, Sequence[str], None] = '1eb6a7def7bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_product_id', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_transactions_invoice_product_id', 'invoice_product_list', ['invoice_product_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transactions_invoice_product_id', type_='foreignkey')
        batch_op.drop_column('invoice_product_id')

    # ### end Alembic commands ###
