"""QtyConverter model fields product_name=unique

Revision ID: e08d0a7cddd8
Revises: fbb5f3ccd8c8
Create Date: 2025-10-24 15:56:42.475795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e08d0a7cddd8'
down_revision: Union[str, Sequence[str], None] = 'fbb5f3ccd8c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_qty_converter', schema=None) as batch_op:
        # batch_op.create_unique_constraint(None, ['product_name'])
        batch_op.create_unique_constraint(
            "uq_product_qty_converter_product_name", ["product_name"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_qty_converter', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(
            "uq_product_qty_converter_product_name",
            type_="unique"
        )

    # ### end Alembic commands ###
