"""tray_no as unique field

Revision ID: ecd76df8cb4f
Revises: 9f438c83bb74
Create Date: 2025-11-07 17:08:56.439718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecd76df8cb4f'
down_revision: Union[str, Sequence[str], None] = '9f438c83bb74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('invoices', schema=None) as batch_op:
#         batch_op.alter_column('invoice_type',
#                existing_type=sa.VARCHAR(length=8),
#                nullable=True)

#     with op.batch_alter_table('rack_master', schema=None) as batch_op:
#         # batch_op.drop_constraint(None, type_='foreignkey')
#         # batch_op.create_foreign_key(None, 'users', ['user_assigned'], ['id'], ondelete='SET NULL')
#         try:
#             batch_op.drop_constraint('rack_master_user_assigned_fkey', type_='foreignkey')
#         except Exception:
#             pass
#         batch_op.create_foreign_key(
#             'rack_master_user_assigned_fkey',
#             'users',
#             ['user_assigned'],
#             ['id'],
#             ondelete='SET NULL'
#         )

#     with op.batch_alter_table('tray_master', schema=None) as batch_op:
#         batch_op.create_unique_constraint(None, ['tray_no'])
#         batch_op.drop_constraint(None, type_='foreignkey')
#         batch_op.create_foreign_key(None, 'invoices', ['current_invoice_no'], ['id'], ondelete='SET NULL')

#     # ### end Alembic commands ###


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('tray_master', schema=None) as batch_op:
#         batch_op.drop_constraint(None, type_='foreignkey')
#         batch_op.create_foreign_key(None, 'invoices', ['current_invoice_no'], ['id'])
#         batch_op.drop_constraint(None, type_='unique')

#     with op.batch_alter_table('rack_master', schema=None) as batch_op:
#         batch_op.drop_constraint(None, type_='foreignkey')
#         batch_op.create_foreign_key(None, 'users', ['user_assigned'], ['id'])

#     with op.batch_alter_table('invoices', schema=None) as batch_op:
#         batch_op.alter_column('invoice_type',
#                existing_type=sa.VARCHAR(length=8),
#                nullable=False)

#     # ### end Alembic commands ###

def upgrade() -> None:
    """Upgrade schema — make tray_no unique only."""
    with op.batch_alter_table('tray_master', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_tray_master_tray_no', ['tray_no'])


def downgrade() -> None:
    """Downgrade schema — remove unique constraint from tray_no."""
    with op.batch_alter_table('tray_master', schema=None) as batch_op:
        batch_op.drop_constraint('uq_tray_master_tray_no', type_='unique')
