"""invoice_type,status rack_master and tray_master set null

Revision ID: f6bbd66f386c
Revises: 3b44d491dbcf
Create Date: 2025-11-17 11:44:09.520827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6bbd66f386c'
down_revision: Union[str, Sequence[str], None] = '3b44d491dbcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def drop_existing_fk(table: str, column: str):
    """Helper to drop existing FK on a column safely across all DBs."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    fks = inspector.get_foreign_keys(table)

    with op.batch_alter_table(table) as batch_op:
        for fk in fks:
            if fk["constrained_columns"] == [column]:
                # batch_op.drop_constraint(fk["name"], type_="foreignkey")
                # SQLite: constraint names are None
                fk_name = fk.get("name")
                if not fk_name:
                    # SQLite case → skip unnamed constraints
                    print(f"Skipping unnamed FK on {table}.{column}")
                    continue

                batch_op.drop_constraint(
                    fk_name,
                    type_="foreignkey"
                )
                

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('invoice_type',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('not_started', 'checking_start', 'checking_end', 'picking_start', 'picking_end', 'completed', name='invoicestatus'),
               existing_nullable=False)

     # --- tray_master ---
    drop_existing_fk("tray_master", "current_invoice_no")
    with op.batch_alter_table("tray_master") as batch_op:
        batch_op.create_foreign_key(
            "fk_tray_invoice",
            "invoices",
            ["current_invoice_no"],
            ["id"], ondelete="SET NULL"
        )
        
    drop_existing_fk("rack_master", "user_assigned")
    # --- rack_master ---
    with op.batch_alter_table("rack_master") as batch_op:
        batch_op.create_foreign_key(
            "fk_rack_invoice",
            "users",
            ["user_assigned"],
            ["id"],
            ondelete="SET NULL"
        )



    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tray_master") as batch_op:
        batch_op.drop_constraint("fk_tray_invoice", type_="foreignkey")

    with op.batch_alter_table("tray_master") as batch_op:
        batch_op.create_foreign_key(
            None,
            "invoices",
            ["current_invoice_no"],
            ["id"],
        )

    with op.batch_alter_table("rack_master") as batch_op:
        batch_op.drop_constraint("fk_rack_invoice", type_="foreignkey")

    with op.batch_alter_table("rack_master") as batch_op:
        batch_op.create_foreign_key(
            None,
            "users",
            ["user_assigned"],
            ["id"],
        )

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('status',
            existing_type=sa.Enum('not_started', 'checking_start', 'checking_end', 'picking_start', 'picking_end', 'completed', name='invoicestatus'),
            type_=sa.VARCHAR(length=11),
            existing_nullable=False)
        batch_op.alter_column('invoice_type',
            existing_type=sa.VARCHAR(length=8),
            nullable=False)

    # ### end Alembic commands ###
