"""create tables 

Revision ID: fbb5f3ccd8c8
Revises: 011e4fed3ce0
Create Date: 2025-10-23 13:17:26.733262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbb5f3ccd8c8'
down_revision: Union[str, Sequence[str], None] = '011e4fed3ce0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_config',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('update_quantity_enabled', sa.Boolean(), nullable=True),
    sa.Column('picker_enabled', sa.Boolean(), nullable=True),
    sa.Column('checker_enabled', sa.Boolean(), nullable=True),
    sa.Column('packed_enabled', sa.Boolean(), nullable=True),
    sa.Column('rack_enabled', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_config_id'), 'system_config', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_type', sa.Enum('admin', 'operator', 'picker', 'packer', 'checker', name='usertypeenum'), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('erp_id', sa.String(), nullable=True),
    sa.Column('erp_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('party_master',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('party_code', sa.String(), nullable=False),
    sa.Column('party_name', sa.String(), nullable=False),
    sa.Column('party_gst', sa.String(), nullable=True),
    sa.Column('party_address', sa.String(), nullable=True),
    sa.Column('party_city', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('party_code')
    )
    op.create_index(op.f('ix_party_master_id'), 'party_master', ['id'], unique=False)
    op.create_table('product_master',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('item_code', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('batch_number', sa.String(), nullable=False),
    sa.Column('expiry_date', sa.String(), nullable=False),
    sa.Column('mfg_date', sa.String(), nullable=False),
    sa.Column('mrp', sa.Float(), nullable=False),
    sa.Column('division', sa.String(), nullable=False),
    sa.Column('obatch', sa.String(), nullable=True),
    sa.Column('barcode1', sa.String(), nullable=True),
    sa.Column('barcode2', sa.String(), nullable=True),
    sa.Column('optional1', sa.String(), nullable=True),
    sa.Column('optional2', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_master_id'), 'product_master', ['id'], unique=False)
    op.create_table('product_qty_converter',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('item_code', sa.String(), nullable=True),
    sa.Column('shipper_val', sa.Integer(), nullable=True),
    sa.Column('box_val', sa.Integer(), nullable=True),
    sa.Column('strip_val', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_qty_converter_id'), 'product_qty_converter', ['id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('priority', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='prioritylevel'), nullable=False),
    sa.Column('invoice_no', sa.String(), nullable=False),
    sa.Column('invoice_date', sa.String(), nullable=False),
    sa.Column('party_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('not_started', 'picked', 'checked', 'packed', 'completed', name='invoicestatus'), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('started_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['party_id'], ['party_master.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_no')
    )
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_table('invoice_metadata',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('invoice_id', sa.String(), nullable=True),
    sa.Column('picker_id', sa.String(), nullable=True),
    sa.Column('picker_start', sa.String(), nullable=True),
    sa.Column('picker_end', sa.String(), nullable=True),
    sa.Column('checker_id', sa.String(), nullable=True),
    sa.Column('checker_start', sa.String(), nullable=True),
    sa.Column('checker_end', sa.String(), nullable=True),
    sa.Column('packer_id', sa.String(), nullable=True),
    sa.Column('packer_start', sa.String(), nullable=True),
    sa.Column('packer_end', sa.String(), nullable=True),
    sa.Column('tray_list', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['checker_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['packer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['picker_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_metadata_id'), 'invoice_metadata', ['id'], unique=False)
    op.create_table('invoice_product_list',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('invoice_id', sa.String(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('batch_number', sa.String(), nullable=False),
    sa.Column('expiry_date', sa.String(), nullable=False),
    sa.Column('mrp', sa.Float(), nullable=False),
    sa.Column('actual_qty', sa.Float(), nullable=False),
    sa.Column('scanned_qty', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_product_list_id'), 'invoice_product_list', ['id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('invoice_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('operation_type', sa.Enum('scan', 'qty_change', name='operationtypeenum'), nullable=False),
    sa.Column('scan_status', sa.Enum('success', 'auto_confirm', 'auto_fallback', 'auto_multi', 'manual', name='scanstatusenum'), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_invoice_product_list_id'), table_name='invoice_product_list')
    op.drop_table('invoice_product_list')
    op.drop_index(op.f('ix_invoice_metadata_id'), table_name='invoice_metadata')
    op.drop_table('invoice_metadata')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_product_qty_converter_id'), table_name='product_qty_converter')
    op.drop_table('product_qty_converter')
    op.drop_index(op.f('ix_product_master_id'), table_name='product_master')
    op.drop_table('product_master')
    op.drop_index(op.f('ix_party_master_id'), table_name='party_master')
    op.drop_table('party_master')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_config_id'), table_name='system_config')
    op.drop_table('system_config')
    # ### end Alembic commands ###
